---
- hosts: 172.31.33.81
  become: yes
  tasks:
  - name: i want to excute linux command directly by playbook
    command: hostname -f
    register: result

  - name: i want to desplay my first task result
    debug:
      msg: "{{result}}"
