---
- hosts: 172.31.33.81
  become: yes
  tasks: 
   - include_tasks: file.yml
   - name: i want to install webserver on ansible node
     apt:
       name: apache2 
       state: present 
 
   - name: i want copy index file into ansible node side 
     template: 
       src: index.j2
       dest: /var/www/html/index.html

   - name: i want to download remote(internet) files
     get_url:
         url: https://get.jenkins.io/war-stable/2.375.2/jenkins.war
         dest: /home/ubuntu/jenkins.war
         force_basic_auth: yes
   