---
- hosts: 172.31.33.81
  become: yes
  vars:
    myvar1: git
    myvar2: tree
    myvars3: wget
  ta sks: 
  - name: install tree
    apt:
      name: "{{myvar1}}"
  - name: i want to display myvar1
    debug:
      msg: "{{myvars1}}"